services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: "${CLOUDFLARE_TUNNEL_TOKEN}"
    restart: unless-stopped

  web:
    image: caddy:2-alpine
    volumes:
      - ../web/dist:/srv:ro
      - ./web.Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
